<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Iodx</RootNamespace>
    <AssemblyName>Iodx</AssemblyName>
    <PackageId>Iodx</PackageId>
    <Version>0.1.0-alpha.1</Version>
    <Authors>Yuri Kravchik</Authors>
    <Description>C# implementation of the IODX data format.</Description>
    <PackageTags>iodx;serialization;configuration;data-format</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://iodx.org/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/kravchik/iodx-cs</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>symbols.nupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Generated/CongoCC/**/test/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <None Include="../../LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
